In [9]:
def pageRank(inputFile):
    print("\n************************ For "+ inputFile+" ************************")
    outputFile=open('output_'+ inputFile,"w")
    
    inputFile=open(inputFile,"r")
    nodes=int(inputFile.readline()) # no of vertices
    graph=np.zeros((nodes,nodes)) # initialize the graph with all zeros

    
    while True:
    #creating the graph matrix from the input 
            line = inputFile.readline()
            if line=="":
                    break
            
            line=line.split()   
            x=int(line[0])
            y=int(line[1])
            graph[y][x]=1
            
    
    
    inputFile.close()

    print("\nNumber of nodes:",nodes)

    print("\nWeb graph:\n",graph)

    M=np.zeros((nodes,nodes))  # Calculate M matrix
    outLink=np.sum(graph, axis=0)
    print("\noutLink: ", outLink)

    for i in range(nodes):
        for j in range(nodes):
            if(graph[i][j] == 1):
                    M[i][j] = 1/outLink[j]

    print("\nM:\n",M)

    r=np.ones(nodes)
    r=r/nodes
    
    
    # Probability b
    b=0.85
    
    A=b*M+(1-b)*(np.ones((nodes,nodes))/nodes) #Matrix A Calculation
    
    print("\nA:\n",A)
    
    print ( "\nExecuting Power Iteration\n")
    
    print("Iteration  0", "\t-> ", np.around(r, decimals=5))
    
    for i in range(99) :
        
        prev_r = r.copy()    
        
        r = np.dot(A,r)
        
        print("Iteration ",i+1, "\t-> ", np.around(r, decimals=5))

        diff = abs(prev_r-r)/prev_r  
        print ("Difference ", "\t-> ", diff)
        
        if(all(i <= 0.05 for i in diff)):
            break



    for i in range(len(r)):

        string ="< "+str(i)+", "+str(round(r[i], 5))+" >\n"
        outputFile.write(string)

    outputFile.close()
    



In [10]:
import numpy as np

inputFiles = ["test1.txt", "test2.txt", "test3.txt", "test4.txt"]


for inputFile in inputFiles:
    pageRank(inputFile)
    



************************ For test1.txt ************************

Number of nodes: 3

Web graph:
 [[1. 1. 0.]
 [1. 0. 1.]
 [0. 1. 0.]]

outLink:  [2. 2. 1.]

M:
 [[0.5 0.5 0. ]
 [0.5 0.  1. ]
 [0.  0.5 0. ]]

A:
 [[0.475 0.475 0.05 ]
 [0.475 0.05  0.9  ]
 [0.05  0.475 0.05 ]]

Executing Power Iteration

Iteration  0 	->  [0.33333 0.33333 0.33333]
Iteration  1 	->  [0.33333 0.475   0.19167]
Difference  	->  [0.    0.425 0.425]
Iteration  2 	->  [0.39354 0.35458 0.25188]
Difference  	->  [0.180625   0.25350877 0.31413043]
Iteration  3 	->  [0.36795 0.43135 0.2007 ]
Difference  	->  [0.06502118 0.2164953  0.20318445]
Iteration  4 	->  [0.3897  0.37697 0.23332]
Difference  	->  [0.0591115  0.12605954 0.16255969]
Iteration  5 	->  [0.37584 0.41395 0.21021]
Difference  	->  [0.03558037 0.09808504 0.09904562]
Iteration  6 	->  [0.38566 0.38841 0.22593]
Difference  	->  [0.02613257 0.06168919 0.0747552 ]
Iteration  7 	->  [0.37898 0.40594 0.21508]
Difference  	->  [0.01731759 0.04513644 0.0480


Number of nodes: 4039

Web graph:
 [[0. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]

outLink:  [347.  16.   9. ...   0.   0.   0.]

M:
 [[0.         0.         0.         ... 0.         0.         0.        ]
 [0.00288184 0.         0.         ... 0.         0.         0.        ]
 [0.00288184 0.         0.         ... 0.         0.         0.        ]
 ...
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]]

A:
 [[3.71379054e-05 3.71379054e-05 3.71379054e-05 ... 3.71379054e-05
  3.71379054e-05 3.71379054e-05]
 [2.48670563e-03 3.71379054e-05 3.71379054e-05 ... 3.71379054e-05
  3.71379054e-05 3.71379054e-05]
 [2.48670563e-03 3.71379054e-05 3.71379054e-05 ... 3.71379054e-05
  3.71379054e-05 3.71379054e-05]
 ...
 [3.7

Difference  	->  [0.20918912 0.20918912 0.20918912 ... 0.20918912 0.20918912 0.20918912]
Iteration  50 	->  [0. 0. 0. ... 0. 0. 0.]
Difference  	->  [0.20918912 0.20918912 0.20918912 ... 0.20918912 0.20918912 0.20918912]
Iteration  51 	->  [0. 0. 0. ... 0. 0. 0.]
Difference  	->  [0.20918912 0.20918912 0.20918912 ... 0.20918912 0.20918912 0.20918912]
Iteration  52 	->  [0. 0. 0. ... 0. 0. 0.]
Difference  	->  [0.20918912 0.20918912 0.20918912 ... 0.20918912 0.20918912 0.20918912]
Iteration  53 	->  [0. 0. 0. ... 0. 0. 0.]
Difference  	->  [0.20918912 0.20918912 0.20918912 ... 0.20918912 0.20918912 0.20918912]
Iteration  54 	->  [0. 0. 0. ... 0. 0. 0.]
Difference  	->  [0.20918912 0.20918912 0.20918912 ... 0.20918912 0.20918912 0.20918912]
Iteration  55 	->  [0. 0. 0. ... 0. 0. 0.]
Difference  	->  [0.20918912 0.20918912 0.20918912 ... 0.20918912 0.20918912 0.20918912]
Iteration  56 	->  [0. 0. 0. ... 0. 0. 0.]
Difference  	->  [0.20918912 0.20918912 0.20918912 ... 0.20918912 0.20918912